name: Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read Python version
        id: read-python-version
        run: echo "::set-output name=python-version::$(cat .python_version)"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.read-python-version.outputs.python-version }}

      - name: Build and deploy docs
        run: |
          git config --global --add safe.directory /__w/local-PTHA-docs/local-PTHA-docs
          pip install mkdocs-material
          mkdocs gh-deploy --force
